### ISSUE TITLE
Validation failure of space-delimited string of Scopes

### ISSUE THREAD

**Issue by CharlesMThomas** [ocadotechnology/sttp-oauth2#117]
I'm running into the following "Predicate failed" error, while attempting to validate / decode a `Scope` of "email profile" included in the client credentials grant access token returned from my identity service. I'm also getting the same error when attempting to define the same `scope` when instantiating the `SttpOauth2ClientCredentialsFutureBackend`

![image](https://user-images.githubusercontent.com/15269939/127043028-3bb68c8b-27a5-450f-88d4-1ee1a732c5d0.png)

I believe the error is being thrown from here:

https://github.com/ocadotechnology/sttp-oauth2/blob/63fe2b0d0a0328a7bfd884a8dff1eb7d7186e438/oauth2/src/main/scala/com/ocadotechnology/sttp/oauth2/common.scala#L25-L30

According to the [OAuth 2.0 spec](https://datatracker.ietf.org/doc/html/rfc6749#section-3.3) a space-delimited, case-sensitive string is a valid value.

Is there possibly an issue with the validation?

I'm using 0.11 of your library. Thanks.

**Comment by majk-p** [comment]
Hi, thank you for reporting the issue. I can confirm it looks like our model doesn't accept scope with spaces. The original intention was to use `Scope` as a representation of singe entry. When client requests scopes we'd use `scopes: Set[Scope]` and provide those separately.

I guess that since some systems use strings with multiple entries, and others would return a list of strings, we can change the regex to allow spaces. This should just be a matter of adjusting the `scopeRegex`.

**Comment by majk-p** [comment]
@CharlesMThomas fixed in https://github.com/ocadotechnology/sttp-oauth2/releases/tag/v0.11.1
